# Site settings
title: My Jekyll Site
description: A simple example site built with Jekyll
baseurl: "/Competitive-Zeqa-Bridge-Website/news" # the subpath of your site, e.g., /blog/
url: "https://beavermon.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Permalinks
permalink: pretty
