# Site settings
title: Zeqa Bridge
description: Made by Jaxfry
baseurl: "/" # the subpath of your site, e.g., /blog/
url: "http://zeqabridge.xyz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Permalinks
permalink: pretty

future: true
